version: "3"
services:
  database:
    image: postgres:9.5
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/referral_app
    depends_on:
      - database
    env_file: .env
    stdin_open: true
    tty: true
volumes:
  db_data:
